moved the navigation bar to the header
galennare/cursed-itsm-board pull request #34
Opened 2023-04-25 19:23 UTC by Owlax

2023-04-25 19:25 UTC, solgaxx submitted a review, later dismissed

2023-04-25 19:43 UTC, galennare requested changes
Could we add some sort of site title? Even if it's embedded in this nav bar?

2023-04-25 20:53 UTC, Owlax commented
> Could we add some sort of site title? Even if it's embedded in this nav bar?

Currently the site title is Cursed ITSM Ticketing System

2023-04-26 22:38 UTC, galennare approved these changes

2023-04-26 23:39 UTC, closed without merging