Feature/profile icons
galennare/cursed-itsm-board pull request #36
Opened 2023-04-25 19:27 UTC by MichaelBrandon-UDel

2023-04-25 19:36 UTC, solgaxx submitted a review, later dismissed

2023-04-25 19:41 UTC, galennare requested changes
From ACs:  The image should be visible somewhere and be unique to each user.

2023-05-02 08:34 UTC, MichaelBrandon-UDel commented
Images can now be customized, will be appended to users once user information is added

2023-05-02 18:13 UTC, galennare requested changes

2023-05-02 20:36 UTC, Owlax approved these changes, later dismissed

2023-05-09 02:37 UTC, galennare approved these changes

2023-05-09 02:38 UTC, galennare approved these changes, later dismissed

2023-05-09 03:12 UTC, solgaxx submitted a review, later dismissed

2023-05-20 17:14 UTC, closed without merging